config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  root 'welcome#index'

  resources :seniors
  resources :locations
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/location.rb
class Location < ApplicationRecord
end

app/models/senior.rb
class Senior < ApplicationRecord
  def name
    first_name + " " + last_initial + "."
  end
  
  # Date and time formatting
  def dt_format
    "%Y-%m-%d %H:%M"
  end
  
  def dt_created
    created_at.strftime(dt_format)
  end
  
  def dt_updated
    updated_at.strftime(dt_format)
  end
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/locations_controller.rb
class LocationsController<ApplicationController
def show
    @location = Location.find(params[:id])
end

def new
@location = Location.new
end

def create
@location = Location.new(location_params)
@location.save
redirect_to @location
end

private
def location_params
params.require(:location).permit(:first_name,:last_name,:location,:contact_name)
end
end

app/controllers/seniors_controller.rb
require 'pry'
class SeniorsController < ApplicationController
  def new
  end

  def index
    @seniors = Senior.find_each(:start => 0, :batch_size => 10)
  end

  def create
     @senior = Senior.new(senior_params)

     @senior.save
     redirect_to @senior
  end

  def show
    @senior = Senior.find(params[:id])
  end

  private
    def senior_params
      params.require(:senior).permit(:first_name, :last_initial, :info)
    end
end

app/controllers/users_controller.rb
#require 'pry'
class UsersController < ApplicationController
  http_basic_authenticate_with name: "ddh", password: "secret", except: [:new,:create]

  def new
  end

  def login
  end 

  def failure
  end

  def success
  end
  
  def req
    log = User.find_by email: params[:user][:email]
    if(params[:user][:password]==log[:password])
      redirect_to log
    else
      redirect_to '/users/login/failure'
    end
  end

  def create
    user = User.new(user_params)
    user.save
    redirect_to '/users/new/success'
  end
    
  def show
    @user = User.find(params[:id])
  end


    private
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/seniors_helper.rb
module SeniorsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EnScheduler</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/locations/new.html.erb
<h1>New Location</h1>

<%= form_with scope: :location, local: true, url:locations_path do |form| %>
  <p>
    <%= form.label :first_name%><br>
    <%= form.text_field :first_name %>
  </p>

  <p>
    <%= form.label :last_name%><br>
    <%= form.text_field :last_name %>
  </p>

  <p>
    <%= form.label :location %><br>
    <%= form.text_area :location %>
  </p>

<p>
    <%= form.label :contact_name %><br>
    <%= form.text_area :contact_name %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/locations/show.html.erb
<p>
  <strong>First Name:</strong>
  <%= @location.first_name %>
</p>

<p>
  <strong>Last Name:</strong>
  <%= @location.last_name %>
</p>

<p>
  <strong>location:</strong>
  <%= @location.location %>
</p>

<p>
  <strong>contact_name:</strong>
  <%= @location.contact_name %>
</p>

app/views/seniors/index.html.erb
<ul>
  <% @seniors.each do |senior| %>
    <li><%= link_to senior.name, senior_path(senior) %></li>
  <% end %>
</ul>

app/views/seniors/new.html.erb
<h1>New Senior</h1>

<%= form_with scope: :senior, local: true, url: seniors_path do |form| %>
  <p>
    <%= form.label :first_name%><br>
    <%= form.text_field :first_name %>
  </p>

  <p>
    <%= form.label :last_initial%><br>
    <%= form.text_field :last_initial %>
  </p>

  <p>
    <%= form.label :info %><br>
    <%= form.text_area :info %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/seniors/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @senior.name %>
</p>

<p>
  <strong>Info:</strong>
  <%= @senior.info %>
</p>

<p>
  <strong>Created at:</strong>
  <%= @senior.dt_created %>
</p>

<p>
  <strong>Updated at:</strong>
  <%= @senior.dt_updated %>
</p>

app/views/users/failure.html.erb
<h1> Password or Email not correct </h1>

app/views/users/login.html.erb
<h1> User Login </h1>

<%= form_with scope: :user, local: true, url: users_login_path do |form| %>
  <p>
    <%= form.label :email %><br>
    <%= form.text_field :email %>
  </p>

  <p>
    <%= form.label :password%><br>
    <%= form.text_field :password %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/users/new.html.erb
<h1>Register New User<h1>

<%= form_with scope: :user, local: true, url: users_path do |form| %>
  <p>
    <%= form.label :first_name%><br>
    <%= form.text_field :first_name %>
  </p>

  <p>
    <%= form.label :last_name%><br>
    <%= form.text_field :last_name %>
  </p>

  <p>
    <%= form.label :email %><br>
    <%= form.text_field :email %>
  </p>

  <p>
    <%= form.label :password%><br>
    <%= form.text_field :password %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/users/show.html.erb
<p>
  <strong>First Name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last Name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>
<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

app/views/users/success.html.erb
<h1>success</h1>

app/views/welcome/index.html.erb
<h1>Welcome to EnScheduler</h1>